"""
Seed data for Compliance Tracker Lite.
Contains full NIST SP 800-171 Rev 2 framework with all 14 families and 110 controls,
plus sample assessment objectives, evidence, POA&M items, and boundary assets.
"""
import uuid
from datetime import datetime
from app.extensions import db
from app.models.framework import Framework
from app.models.control_family import ControlFamily
from app.models.control import Control
from app.models.assessment_objective import AssessmentObjective
from app.models.evidence import Evidence
from app.models.poam import POAMItem
from app.models.boundary_asset import BoundaryAsset

# Deterministic UUID generation using uuid5
NAMESPACE = uuid.UUID('a1b2c3d4-e5f6-7890-abcd-ef1234567890')


def make_id(name):
    """Generate a deterministic UUID from a name string."""
    return str(uuid.uuid5(NAMESPACE, name))


def seed():
    """Seed the database with NIST SP 800-171 Rev 2 data and sample assessment state."""

    # =========================================================================
    # FRAMEWORK
    # =========================================================================
    framework_id = make_id('nist-800-171-r2')
    framework = Framework(
        id=framework_id,
        name='NIST SP 800-171 Rev 2',
        version='Rev 2',
        description='Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations. '
                    'This publication provides federal agencies with a set of recommended security requirements '
                    'for protecting the confidentiality of CUI when it is resident in nonfederal systems and organizations.',
        total_controls=110,
        total_objectives=320,
        session_id='__default__',
    )
    db.session.add(framework)

    # =========================================================================
    # CONTROL FAMILIES
    # =========================================================================
    families_data = [
        ('AC', 'Access Control', 'Limit system access to authorized users, processes acting on behalf of authorized users, and devices.', 22, 1),
        ('AT', 'Awareness and Training', 'Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.', 3, 2),
        ('AU', 'Audit and Accountability', 'Create, protect, and retain system audit records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful, unauthorized, or inappropriate system activity; and ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable for their actions.', 9, 3),
        ('CM', 'Configuration Management', 'Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles; and establish and enforce security configuration settings for information technology products employed in organizational systems.', 9, 4),
        ('IA', 'Identification and Authentication', 'Identify system users, processes acting on behalf of users, and devices; and authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems.', 11, 5),
        ('IR', 'Incident Response', 'Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities; and track, document, and report incidents to designated officials and/or authorities.', 3, 6),
        ('MA', 'Maintenance', 'Perform maintenance on organizational systems; and provide effective controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.', 6, 7),
        ('MP', 'Media Protection', 'Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital; limit access to CUI on system media to authorized users; and sanitize or destroy system media containing CUI before disposal or release for reuse.', 9, 8),
        ('PS', 'Personnel Security', 'Screen individuals prior to authorizing access to organizational systems containing CUI; and ensure that CUI and organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.', 2, 9),
        ('PE', 'Physical Protection', 'Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals; protect and monitor the physical facility and support infrastructure for organizational systems; provide supporting utilities for organizational systems; protect organizational systems against environmental hazards; and provide appropriate environmental controls in facilities containing organizational systems.', 6, 10),
        ('RA', 'Risk Assessment', 'Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI.', 3, 11),
        ('CA', 'Security Assessment', 'Periodically assess the security controls in organizational systems to determine if the controls are effective in their application; develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems; monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls; and develop, document, and periodically update system security plans.', 4, 12),
        ('SC', 'System and Communications Protection', 'Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems; and employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.', 16, 13),
        ('SI', 'System and Information Integrity', 'Identify, report, and correct system flaws in a timely manner; provide protection from malicious code at designated locations within organizational systems; and monitor system security alerts and advisories and take action in response.', 7, 14),
    ]

    family_map = {}
    for code, name, desc, count, sort in families_data:
        fid = make_id(f'family-{code}')
        family = ControlFamily(
            id=fid,
            framework_id=framework_id,
            family_code=code,
            name=name,
            description=desc,
            control_count=count,
            sort_order=sort,
            session_id='__default__',
        )
        db.session.add(family)
        family_map[code] = fid

    # =========================================================================
    # ALL 110 CONTROLS — NIST SP 800-171 Rev 2
    # =========================================================================
    # Format: (number, title, requirement_text, plain_english, control_type, weight)

    controls_data = {
        'AC': [
            ('3.1.1', 'Authorized Access Control',
             'Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).',
             'Only allow people and systems that are supposed to have access to actually get in. No unauthorized users allowed.',
             'basic', 5),
            ('3.1.2', 'Transaction and Function Control',
             'Limit system access to the types of transactions and functions that authorized users are permitted to execute.',
             'Even authorized users should only be able to do what their role allows. A regular employee should not have admin access.',
             'basic', 5),
            ('3.1.3', 'CUI Flow Enforcement',
             'Control the flow of CUI in accordance with approved authorizations.',
             'Control how sensitive information moves between systems and people. CUI should only flow where it is approved to go.',
             'derived', 3),
            ('3.1.4', 'Separation of Duties',
             'Separate the duties of individuals to reduce the risk of malevolent activity without collusion.',
             'Do not let one person have all the keys. Split responsibilities so no single person can cause harm alone.',
             'derived', 3),
            ('3.1.5', 'Least Privilege',
             'Employ the principle of least privilege, including for specific security functions and privileged accounts.',
             'Give people only the minimum access they need to do their job. Nothing more.',
             'derived', 5),
            ('3.1.6', 'Non-Privileged Account Use',
             'Use non-privileged accounts or roles when accessing nonsecurity functions.',
             'Admins should use regular accounts for everyday tasks and only use their admin account when doing admin work.',
             'derived', 3),
            ('3.1.7', 'Privileged Function Restriction',
             'Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs.',
             'Regular users should not be able to run admin commands, and if they try, it should be logged.',
             'derived', 3),
            ('3.1.8', 'Unsuccessful Logon Attempts',
             'Limit unsuccessful logon attempts.',
             'Lock accounts or slow down login attempts after too many bad password tries.',
             'derived', 3),
            ('3.1.9', 'Privacy and Security Notices',
             'Provide privacy and security notices consistent with applicable CUI rules.',
             'Show login banners and warnings about authorized use before users log in.',
             'derived', 1),
            ('3.1.10', 'Session Lock',
             'Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.',
             'Automatically lock the screen after inactivity so nobody can walk up and see sensitive data.',
             'derived', 3),
            ('3.1.11', 'Session Termination',
             'Terminate (automatically) a user session after a defined condition.',
             'Automatically log users out after a set period of inactivity or other trigger conditions.',
             'derived', 1),
            ('3.1.12', 'Remote Access Control',
             'Monitor and control remote access sessions.',
             'Keep track of who is accessing systems remotely and have controls in place to manage those connections.',
             'derived', 5),
            ('3.1.13', 'Remote Access Confidentiality',
             'Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.',
             'Use encryption (like VPN) for all remote connections to protect data in transit.',
             'derived', 5),
            ('3.1.14', 'Remote Access Routing',
             'Route remote access via managed access control points.',
             'All remote connections must go through approved entry points like a VPN gateway, not direct connections.',
             'derived', 3),
            ('3.1.15', 'Privileged Remote Access',
             'Authorize remote execution of privileged commands and remote access to security-relevant information.',
             'Admin-level remote access needs special authorization and should be tightly controlled.',
             'derived', 3),
            ('3.1.16', 'Wireless Access Authorization',
             'Authorize wireless access prior to allowing such connections.',
             'Wi-Fi access must be approved and controlled. No rogue wireless access points.',
             'derived', 3),
            ('3.1.17', 'Wireless Access Protection',
             'Protect wireless access using authentication and encryption.',
             'Wi-Fi networks must use strong authentication (WPA2/3 Enterprise) and encryption.',
             'derived', 3),
            ('3.1.18', 'Mobile Device Connection',
             'Control connection of mobile devices.',
             'Manage which mobile devices can connect to your network and enforce security policies on them.',
             'derived', 1),
            ('3.1.19', 'Encrypt CUI on Mobile Devices',
             'Encrypt CUI on mobile devices and mobile computing platforms.',
             'If sensitive data is on a laptop, phone, or tablet, it must be encrypted.',
             'derived', 5),
            ('3.1.20', 'External System Connections',
             'Verify and control/limit connections to and use of external systems.',
             'Control which outside systems can connect to yours and limit what they can access.',
             'derived', 3),
            ('3.1.21', 'Portable Storage Use',
             'Limit use of portable storage devices on external systems.',
             'Restrict the use of USB drives and other portable media, especially on outside systems.',
             'derived', 1),
            ('3.1.22', 'Publicly Accessible Content',
             'Control information posted or processed on publicly accessible systems.',
             'Make sure no CUI ends up on public-facing websites or systems.',
             'derived', 3),
        ],
        'AT': [
            ('3.2.1', 'Security Awareness',
             'Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.',
             'Train everyone on security risks and policies. People need to know the rules and why they matter.',
             'basic', 3),
            ('3.2.2', 'Role-Based Training',
             'Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.',
             'Give people specific security training for their roles. An admin needs different training than a regular user.',
             'basic', 3),
            ('3.2.3', 'Insider Threat Awareness',
             'Provide security awareness training on recognizing and reporting potential indicators of insider threat.',
             'Train people to spot and report suspicious behavior from insiders, like unusual data access patterns.',
             'derived', 1),
        ],
        'AU': [
            ('3.3.1', 'System Auditing',
             'Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.',
             'Log what happens on your systems so you can investigate if something goes wrong.',
             'basic', 5),
            ('3.3.2', 'User Accountability',
             'Ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable for their actions.',
             'Every action in the system should be traceable to a specific person. No shared accounts for CUI systems.',
             'basic', 5),
            ('3.3.3', 'Event Review',
             'Review and update logged events.',
             'Regularly review your audit logs and update what events you are tracking.',
             'derived', 1),
            ('3.3.4', 'Audit Failure Alerting',
             'Alert in the event of an audit logging process failure.',
             'Get notified immediately if your logging system stops working.',
             'derived', 1),
            ('3.3.5', 'Audit Review and Reporting',
             'Correlate audit record review, analysis, and reporting processes to support organizational processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity.',
             'Connect your log analysis to your incident response process so suspicious activity gets investigated.',
             'derived', 3),
            ('3.3.6', 'Audit Reduction',
             'Provide audit record reduction and report generation to support on-demand analysis and reporting.',
             'Have tools to search, filter, and generate reports from your audit logs.',
             'derived', 1),
            ('3.3.7', 'Authoritative Time Source',
             'Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.',
             'Sync all system clocks with NTP so audit log timestamps are accurate and consistent.',
             'derived', 1),
            ('3.3.8', 'Audit Protection',
             'Protect audit information and audit logging tools from unauthorized access, modification, and deletion.',
             'Lock down your logs so attackers cannot delete or modify them to cover their tracks.',
             'derived', 3),
            ('3.3.9', 'Audit Management Limitation',
             'Limit management of audit logging functionality to a subset of privileged users.',
             'Only a few trusted admins should be able to change audit logging settings.',
             'derived', 1),
        ],
        'CM': [
            ('3.4.1', 'System Baseline Configuration',
             'Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles.',
             'Know exactly what hardware and software you have and keep a documented standard configuration for each.',
             'basic', 5),
            ('3.4.2', 'Security Configuration Enforcement',
             'Establish and enforce security configuration settings for information technology products employed in organizational systems.',
             'Use security hardening guides (like CIS Benchmarks or DISA STIGs) and enforce those settings.',
             'basic', 5),
            ('3.4.3', 'System Change Tracking',
             'Track, review, approve or disapprove, and log changes to organizational systems.',
             'Have a change management process so all system changes are tracked and approved before implementation.',
             'derived', 3),
            ('3.4.4', 'Security Impact Analysis',
             'Analyze the security impact of changes prior to implementation.',
             'Before making changes, check whether they could introduce security problems.',
             'derived', 1),
            ('3.4.5', 'Access Restrictions for Change',
             'Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.',
             'Only authorized people should be able to make changes to systems, and those changes need proper access controls.',
             'derived', 3),
            ('3.4.6', 'Least Functionality',
             'Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.',
             'Disable or remove unnecessary software, services, and ports. Only run what you actually need.',
             'derived', 3),
            ('3.4.7', 'Nonessential Programs Restriction',
             'Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.',
             'Block unnecessary programs and network services. If you do not need it, turn it off.',
             'derived', 1),
            ('3.4.8', 'Application Execution Policy',
             'Apply deny-by-exception (blocklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (allowlisting) policy to allow the execution of authorized software.',
             'Use application allowlisting or blocklisting to control which software can run on your systems.',
             'derived', 3),
            ('3.4.9', 'User-Installed Software Control',
             'Control and monitor user-installed software.',
             'Restrict and monitor what software users can install. No unauthorized software on CUI systems.',
             'derived', 1),
        ],
        'IA': [
            ('3.5.1', 'User Identification',
             'Identify system users, processes acting on behalf of users, and devices.',
             'Every user, automated process, and device on your network must have a unique identity.',
             'basic', 5),
            ('3.5.2', 'Entity Authentication',
             'Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems.',
             'Verify identity before granting access. Passwords, MFA, or certificates for users; certificates or tokens for devices.',
             'basic', 5),
            ('3.5.3', 'Multifactor Authentication',
             'Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.',
             'Require MFA for all admin accounts and for any network access to regular accounts.',
             'derived', 5),
            ('3.5.4', 'Replay-Resistant Authentication',
             'Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.',
             'Use authentication methods that cannot be replayed by attackers who capture login traffic.',
             'derived', 3),
            ('3.5.5', 'Identifier Reuse Prevention',
             'Prevent reuse of identifiers for a defined period.',
             'Do not reuse usernames or system IDs for a reasonable period after someone leaves.',
             'derived', 1),
            ('3.5.6', 'Identifier Disabling',
             'Disable identifiers after a defined period of inactivity.',
             'Automatically disable accounts that have not been used for a set period (like 90 days).',
             'derived', 1),
            ('3.5.7', 'Password Complexity',
             'Enforce a minimum password complexity and change of characters when new passwords are created.',
             'Require strong passwords with mix of character types. New passwords must differ from old ones.',
             'derived', 3),
            ('3.5.8', 'Password Reuse Prohibition',
             'Prohibit password reuse for a specified number of generations.',
             'Do not allow people to reuse their last several passwords.',
             'derived', 1),
            ('3.5.9', 'Temporary Password Change',
             'Allow temporary password use for system logons with an immediate change to a permanent password.',
             'When issuing temporary passwords, force users to change them immediately upon first login.',
             'derived', 1),
            ('3.5.10', 'Cryptographic Password Protection',
             'Store and transmit only cryptographically-protected passwords.',
             'Never store passwords in plain text. Always hash stored passwords and encrypt passwords in transit.',
             'derived', 3),
            ('3.5.11', 'Obscure Authentication Feedback',
             'Obscure feedback of authentication information.',
             'Do not show passwords on screen when people type them. Mask the input.',
             'derived', 1),
        ],
        'IR': [
            ('3.6.1', 'Incident Handling',
             'Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities.',
             'Have a documented incident response plan and capability. Know what to do when something goes wrong.',
             'basic', 5),
            ('3.6.2', 'Incident Reporting',
             'Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization.',
             'When incidents happen, document them and report to the right people, including DIBCAC if required.',
             'basic', 3),
            ('3.6.3', 'Incident Response Testing',
             'Test the organizational incident response capability.',
             'Practice your incident response plan regularly through tabletop exercises or simulations.',
             'derived', 1),
        ],
        'MA': [
            ('3.7.1', 'System Maintenance',
             'Perform maintenance on organizational systems.',
             'Regularly maintain and patch your systems. Keep them up to date.',
             'basic', 3),
            ('3.7.2', 'System Maintenance Controls',
             'Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.',
             'Control who performs maintenance and what tools they use. Supervise external maintenance personnel.',
             'basic', 3),
            ('3.7.3', 'Equipment Sanitization',
             'Ensure equipment removed for off-site maintenance is sanitized of any CUI.',
             'Before sending equipment out for repair, remove all sensitive data from it.',
             'derived', 3),
            ('3.7.4', 'Media Inspection',
             'Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.',
             'Scan any maintenance media (USB drives, diagnostic CDs) for malware before plugging them in.',
             'derived', 1),
            ('3.7.5', 'Nonlocal Maintenance',
             'Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.',
             'Use MFA for remote maintenance sessions and close the connection when done.',
             'derived', 3),
            ('3.7.6', 'Maintenance Personnel Supervision',
             'Supervise the maintenance activities of maintenance personnel without required access authorization.',
             'If a vendor tech works on your systems and does not have clearance, someone authorized must watch them.',
             'derived', 1),
        ],
        'MP': [
            ('3.8.1', 'Media Protection',
             'Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital.',
             'Lock up media with sensitive data on it, both paper documents and digital media like hard drives.',
             'basic', 3),
            ('3.8.2', 'Media Access Limitation',
             'Limit access to CUI on system media to authorized users.',
             'Only people who need it should be able to access media containing CUI.',
             'basic', 3),
            ('3.8.3', 'Media Sanitization',
             'Sanitize or destroy system media containing CUI before disposal or release for reuse.',
             'Wipe or destroy hard drives and other media before throwing them away or giving them to someone else.',
             'derived', 5),
            ('3.8.4', 'Media Markings',
             'Mark media with necessary CUI markings and distribution limitations.',
             'Label media containing CUI so people know what is on it and who can access it.',
             'derived', 1),
            ('3.8.5', 'Media Accountability',
             'Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.',
             'Track who has CUI media and where it goes, especially when transporting it.',
             'derived', 1),
            ('3.8.6', 'Portable Storage Encryption',
             'Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.',
             'Encrypt CUI on USB drives, external hard drives, and other portable media.',
             'derived', 3),
            ('3.8.7', 'Removable Media Control',
             'Control the use of removable media on system components.',
             'Manage and restrict the use of USB drives and other removable media on your systems.',
             'derived', 1),
            ('3.8.8', 'Shared Media Prohibition',
             'Prohibit the use of portable storage devices when such devices have no identifiable owner.',
             'Do not allow random USB drives. Every piece of removable media must have a known owner.',
             'derived', 1),
            ('3.8.9', 'Backup Storage Protection',
             'Protect the confidentiality of backup CUI at storage locations.',
             'Encrypt your backups and store them securely. Backups of CUI need the same protection as the originals.',
             'derived', 3),
        ],
        'PS': [
            ('3.9.1', 'Personnel Screening',
             'Screen individuals prior to authorizing access to organizational systems containing CUI.',
             'Do background checks before giving people access to systems with sensitive data.',
             'basic', 3),
            ('3.9.2', 'Personnel Actions',
             'Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers.',
             'When someone leaves or changes roles, immediately revoke their access and recover all CUI materials.',
             'basic', 3),
        ],
        'PE': [
            ('3.10.1', 'Physical Access Limitation',
             'Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals.',
             'Lock your server rooms and restrict physical access to computing equipment.',
             'basic', 3),
            ('3.10.2', 'Physical Facility Protection',
             'Protect and monitor the physical facility and support infrastructure for organizational systems.',
             'Monitor who enters your facilities with cameras, badge readers, and visitor logs.',
             'basic', 3),
            ('3.10.3', 'Visitor Escort',
             'Escort visitors and monitor visitor activity.',
             'Visitors must be escorted and watched while in areas with CUI systems.',
             'derived', 1),
            ('3.10.4', 'Physical Access Logs',
             'Maintain audit logs of physical access.',
             'Keep records of who accessed server rooms and other controlled areas.',
             'derived', 1),
            ('3.10.5', 'Physical Access Devices',
             'Control and manage physical access devices.',
             'Manage keys, access cards, and combinations. Track who has what.',
             'derived', 1),
            ('3.10.6', 'Alternative Work Sites',
             'Enforce safeguarding measures for CUI at alternate work sites.',
             'Home offices and other remote work locations need appropriate security for CUI.',
             'derived', 3),
        ],
        'RA': [
            ('3.11.1', 'Risk Assessment',
             'Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI.',
             'Regularly perform risk assessments to identify and understand your security risks.',
             'basic', 3),
            ('3.11.2', 'Vulnerability Scanning',
             'Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.',
             'Run regular vulnerability scans on your systems and scan again when new vulnerabilities are announced.',
             'derived', 5),
            ('3.11.3', 'Vulnerability Remediation',
             'Remediate vulnerabilities in accordance with risk assessments.',
             'Fix the vulnerabilities you find, prioritizing by risk level. Patch critical issues first.',
             'derived', 3),
        ],
        'CA': [
            ('3.12.1', 'Security Control Assessment',
             'Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.',
             'Regularly test whether your security controls actually work as intended.',
             'basic', 3),
            ('3.12.2', 'Plans of Action',
             'Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems.',
             'Create POA&M documents to track how and when you will fix identified security gaps.',
             'basic', 3),
            ('3.12.3', 'Continuous Monitoring',
             'Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.',
             'Continuously monitor your security posture, not just during annual assessments.',
             'derived', 3),
            ('3.12.4', 'System Security Plan',
             'Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.',
             'Write and maintain a System Security Plan (SSP) that documents how you protect CUI.',
             'derived', 5),
        ],
        'SC': [
            ('3.13.1', 'Boundary Protection',
             'Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems.',
             'Use firewalls and monitoring at your network perimeter and between network segments.',
             'basic', 5),
            ('3.13.2', 'Security Engineering',
             'Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems.',
             'Design your systems with security built in from the start, not bolted on after.',
             'basic', 3),
            ('3.13.3', 'User-Functionality Separation',
             'Separate user functionality from system management functionality.',
             'Keep management interfaces separate from regular user interfaces.',
             'derived', 1),
            ('3.13.4', 'Shared Resource Control',
             'Prevent unauthorized and unintended information transfer via shared system resources.',
             'Ensure data cannot leak between users through shared memory, temp files, or other shared resources.',
             'derived', 1),
            ('3.13.5', 'Public Access System Separation',
             'Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.',
             'Put public-facing systems in a DMZ, separated from internal networks.',
             'derived', 5),
            ('3.13.6', 'Network Communication by Exception',
             'Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).',
             'Default-deny firewall rules. Block everything and only allow what is needed.',
             'derived', 5),
            ('3.13.7', 'Split Tunneling Prevention',
             'Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling).',
             'When connected to VPN, block direct internet access to prevent data from bypassing security controls.',
             'derived', 3),
            ('3.13.8', 'CUI Transmission Encryption',
             'Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.',
             'Encrypt CUI when it travels over the network. Use TLS, VPN, or other encryption.',
             'derived', 5),
            ('3.13.9', 'Network Disconnect',
             'Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.',
             'Close network connections when sessions end or after inactivity timeout.',
             'derived', 1),
            ('3.13.10', 'Cryptographic Key Management',
             'Establish and manage cryptographic keys for cryptography employed in organizational systems.',
             'Properly manage encryption keys with secure generation, storage, rotation, and destruction.',
             'derived', 3),
            ('3.13.11', 'CUI Encryption at Rest',
             'Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.',
             'Use FIPS 140-2 validated encryption modules for protecting CUI.',
             'derived', 5),
            ('3.13.12', 'Collaborative Device Control',
             'Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.',
             'Prevent remote activation of cameras and microphones and show indicator lights when they are active.',
             'derived', 1),
            ('3.13.13', 'Mobile Code Control',
             'Control and monitor the use of mobile code.',
             'Control the use of JavaScript, ActiveX, and other mobile code technologies.',
             'derived', 1),
            ('3.13.14', 'VoIP Protection',
             'Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.',
             'If you use VoIP, apply appropriate security controls and monitoring.',
             'derived', 1),
            ('3.13.15', 'Communications Authenticity',
             'Protect the authenticity of communications sessions.',
             'Use session authentication to protect against hijacking and man-in-the-middle attacks.',
             'derived', 3),
            ('3.13.16', 'CUI at Rest Protection',
             'Protect the confidentiality of CUI at rest.',
             'Encrypt CUI wherever it is stored on disk drives, databases, and storage systems.',
             'derived', 5),
        ],
        'SI': [
            ('3.14.1', 'Flaw Remediation',
             'Identify, report, and correct information and system flaws in a timely manner.',
             'Patch your systems promptly. When vulnerabilities are found, fix them quickly.',
             'basic', 5),
            ('3.14.2', 'Malicious Code Protection',
             'Provide protection from malicious code at appropriate locations within organizational systems.',
             'Run antivirus/anti-malware on all systems and keep it updated.',
             'basic', 5),
            ('3.14.3', 'Security Alerts',
             'Monitor system security alerts and advisories and take action in response.',
             'Subscribe to security bulletins and act on them when they affect your systems.',
             'derived', 3),
            ('3.14.4', 'Update Malicious Code Protection',
             'Update malicious code protection mechanisms when new releases are available.',
             'Keep antivirus definitions and anti-malware signatures up to date.',
             'derived', 3),
            ('3.14.5', 'System and Network Scanning',
             'Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed.',
             'Run regular system scans and scan files from external sources in real-time.',
             'derived', 3),
            ('3.14.6', 'Inbound Traffic Monitoring',
             'Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks.',
             'Watch your network traffic for signs of attacks using IDS/IPS and network monitoring tools.',
             'derived', 5),
            ('3.14.7', 'Unauthorized Use Identification',
             'Identify unauthorized use of organizational systems.',
             'Detect and alert on unauthorized system usage, like logins from unusual locations or times.',
             'derived', 3),
        ],
    }

    # =========================================================================
    # IMPLEMENTATION STATUS ASSIGNMENT
    # =========================================================================
    # Target distribution: 60 implemented, 20 partially, 15 planned, 10 not_impl, 5 n/a

    # Assign statuses by family to create a realistic distribution
    status_assignments = {
        # Distribution target: 60 implemented, 20 partially_implemented, 15 planned,
        #                       10 not_implemented, 5 not_applicable = 110 total
        #
        # Distribution: 51 implemented, 22 partially_implemented, 14 planned,
        #               18 not_implemented, 5 not_applicable = 110 total
        # Calculated SPRS score: approximately -22
        #
        # AC family (22): 11 impl, 4 partial, 3 planned, 3 not_impl, 1 n/a
        '3.1.1': 'implemented',
        '3.1.2': 'implemented',
        '3.1.3': 'partially_implemented',
        '3.1.4': 'implemented',
        '3.1.5': 'partially_implemented',
        '3.1.6': 'implemented',
        '3.1.7': 'implemented',
        '3.1.8': 'implemented',
        '3.1.9': 'implemented',
        '3.1.10': 'implemented',
        '3.1.11': 'implemented',
        '3.1.12': 'partially_implemented',
        '3.1.13': 'implemented',
        '3.1.14': 'planned',
        '3.1.15': 'not_implemented',
        '3.1.16': 'implemented',
        '3.1.17': 'partially_implemented',
        '3.1.18': 'planned',
        '3.1.19': 'not_implemented',
        '3.1.20': 'not_implemented',
        '3.1.21': 'not_applicable',
        '3.1.22': 'planned',
        # AT family (3): 2 impl, 1 partial
        '3.2.1': 'implemented',
        '3.2.2': 'implemented',
        '3.2.3': 'partially_implemented',
        # AU family (9): 4 impl, 2 partial, 1 planned, 2 not_impl
        '3.3.1': 'implemented',
        '3.3.2': 'implemented',
        '3.3.3': 'partially_implemented',
        '3.3.4': 'planned',
        '3.3.5': 'not_implemented',
        '3.3.6': 'implemented',
        '3.3.7': 'implemented',
        '3.3.8': 'partially_implemented',
        '3.3.9': 'not_implemented',
        # CM family (9): 4 impl, 2 partial, 1 planned, 2 not_impl
        '3.4.1': 'implemented',
        '3.4.2': 'partially_implemented',
        '3.4.3': 'implemented',
        '3.4.4': 'implemented',
        '3.4.5': 'partially_implemented',
        '3.4.6': 'not_implemented',
        '3.4.7': 'planned',
        '3.4.8': 'not_implemented',
        '3.4.9': 'implemented',
        # IA family (11): 6 impl, 2 partial, 1 planned, 1 not_impl, 1 n/a
        '3.5.1': 'implemented',
        '3.5.2': 'implemented',
        '3.5.3': 'not_implemented',
        '3.5.4': 'implemented',
        '3.5.5': 'implemented',
        '3.5.6': 'implemented',
        '3.5.7': 'partially_implemented',
        '3.5.8': 'implemented',
        '3.5.9': 'not_applicable',
        '3.5.10': 'partially_implemented',
        '3.5.11': 'planned',
        # IR family (3): 1 impl, 1 partial, 1 planned
        '3.6.1': 'implemented',
        '3.6.2': 'partially_implemented',
        '3.6.3': 'planned',
        # MA family (6): 3 impl, 1 partial, 1 planned, 1 not_impl
        '3.7.1': 'implemented',
        '3.7.2': 'implemented',
        '3.7.3': 'partially_implemented',
        '3.7.4': 'not_implemented',
        '3.7.5': 'planned',
        '3.7.6': 'implemented',
        # MP family (9): 3 impl, 2 partial, 2 planned, 1 not_impl, 1 n/a
        '3.8.1': 'implemented',
        '3.8.2': 'implemented',
        '3.8.3': 'not_implemented',
        '3.8.4': 'partially_implemented',
        '3.8.5': 'planned',
        '3.8.6': 'partially_implemented',
        '3.8.7': 'implemented',
        '3.8.8': 'not_applicable',
        '3.8.9': 'planned',
        # PS family (2): 2 impl
        '3.9.1': 'implemented',
        '3.9.2': 'implemented',
        # PE family (6): 4 impl, 1 partial, 1 not_impl
        '3.10.1': 'implemented',
        '3.10.2': 'implemented',
        '3.10.3': 'implemented',
        '3.10.4': 'partially_implemented',
        '3.10.5': 'not_implemented',
        '3.10.6': 'implemented',
        # RA family (3): 1 impl, 1 partial, 1 not_impl
        '3.11.1': 'implemented',
        '3.11.2': 'partially_implemented',
        '3.11.3': 'not_implemented',
        # CA family (4): 1 impl, 1 partial, 1 planned, 1 not_impl
        '3.12.1': 'implemented',
        '3.12.2': 'partially_implemented',
        '3.12.3': 'planned',
        '3.12.4': 'not_implemented',
        # SC family (16): 6 impl, 3 partial, 2 planned, 3 not_impl, 2 n/a
        '3.13.1': 'implemented',
        '3.13.2': 'partially_implemented',
        '3.13.3': 'implemented',
        '3.13.4': 'not_implemented',
        '3.13.5': 'implemented',
        '3.13.6': 'implemented',
        '3.13.7': 'planned',
        '3.13.8': 'implemented',
        '3.13.9': 'implemented',
        '3.13.10': 'partially_implemented',
        '3.13.11': 'not_implemented',
        '3.13.12': 'not_applicable',
        '3.13.13': 'not_implemented',
        '3.13.14': 'not_applicable',
        '3.13.15': 'partially_implemented',
        '3.13.16': 'planned',
        # SI family (7): 3 impl, 1 partial, 1 planned, 2 not_impl
        '3.14.1': 'implemented',
        '3.14.2': 'implemented',
        '3.14.3': 'implemented',
        '3.14.4': 'partially_implemented',
        '3.14.5': 'planned',
        '3.14.6': 'not_implemented',
        '3.14.7': 'not_implemented',
    }

    # Implementation notes for controls that are not fully implemented
    impl_notes = {
        '3.1.3': 'Data flow diagrams completed. DLP solution procurement in progress.',
        '3.1.5': 'Least privilege policy defined. Need to complete RBAC review for all CUI applications.',
        '3.1.12': 'VPN in place for most users. Need to extend to remaining contractor workforce.',
        '3.1.14': 'Remote access routing policy drafted. Need managed access control point implementation.',
        '3.1.15': 'No privileged remote access controls. Need policy and technical enforcement for admin sessions.',
        '3.1.17': 'WPA2-Enterprise deployed on main campus. Branch office still on WPA2-PSK.',
        '3.1.18': 'MDM solution selected (Intune). Rollout begins March 2026.',
        '3.1.19': 'Mobile device encryption not enforced. BitLocker on 40% of laptops only.',
        '3.1.20': 'External system connections not verified or controlled. Need connection authorization process.',
        '3.1.22': 'Web publishing workflow updated. Automated CUI scanning tool in evaluation.',
        '3.2.3': 'Annual training includes insider threat module. Need quarterly refreshers.',
        '3.3.3': 'Log review process documented. Need to increase review frequency to weekly.',
        '3.3.4': 'SIEM alerting rules drafted. Deployment pending SIEM procurement.',
        '3.3.5': 'No automated correlation of audit records with incident response. Need SIEM integration.',
        '3.3.8': 'Audit logs backed up but access controls need tightening. Working on immutable log storage.',
        '3.3.9': 'Audit log admin roles not yet restricted. Need RBAC update for SIEM.',
        '3.4.2': 'CIS Benchmarks applied to Windows servers. Linux hardening guide still in draft.',
        '3.4.5': 'Change management process exists but physical access restrictions for changes not enforced.',
        '3.4.6': 'Least functionality principle not applied. Systems running unnecessary services and software.',
        '3.4.7': 'Firewall rules block most services. Application-level filtering not yet deployed.',
        '3.4.8': 'Application allowlisting evaluated. Deployment scheduled for Q2 2026.',
        '3.5.3': 'MFA not deployed. Duo evaluation complete but procurement and deployment not started.',
        '3.5.7': 'Password complexity partially enforced in AD. Need to extend to all service and local accounts.',
        '3.5.10': 'Most systems use hashed passwords. Legacy ERP system needs upgrade for cryptographic password storage.',
        '3.5.11': 'Password masking needs implementation across all custom applications.',
        '3.6.2': 'Incident reporting process exists but documentation and escalation paths need formalization.',
        '3.6.3': 'Tabletop exercise planned for March 2026. IR plan tested informally.',
        '3.7.3': 'Process documented for server equipment. Need to add procedures for network devices.',
        '3.7.4': 'No formal media scanning process for maintenance tools.',
        '3.7.5': 'Remote maintenance sessions require VPN but MFA enforcement is pending.',
        '3.8.3': 'No media sanitization procedures or equipment. NIST 800-88 procedures not implemented.',
        '3.8.4': 'Digital media marking policy drafted. Physical label templates created.',
        '3.8.5': 'Media accountability tracking planned. Chain of custody forms in development.',
        '3.8.6': 'Encrypted USB drives purchased for IT team. Full rollout pending.',
        '3.8.9': 'Backup encryption planned. Currently backups stored without encryption at offsite location.',
        '3.10.4': 'Badge reader logs maintained. Need centralized log aggregation.',
        '3.10.5': 'Key inventory incomplete. Badge access system needs audit.',
        '3.11.2': 'Nessus scans run monthly on servers. Need to add workstation and application scanning.',
        '3.11.3': 'Vulnerability remediation process not established. Findings tracked ad hoc, no formal SLA.',
        '3.12.2': 'POA&M process initiated but needs formalization and regular review cadence.',
        '3.12.3': 'Continuous monitoring not implemented. Only annual assessment currently performed.',
        '3.12.4': 'System Security Plan not documented. Need to hire consultant or assign dedicated resource.',
        '3.13.2': 'Network segmentation in place. Application architecture review pending.',
        '3.13.4': 'Shared resource controls not implemented. Workstations allow information transfer via shared resources.',
        '3.13.7': 'Split tunneling policy defined. Technical enforcement on VPN client pending.',
        '3.13.10': 'Key management procedures drafted. Need formal key lifecycle documentation.',
        '3.13.11': 'FIPS-validated cryptography not deployed. Current encryption modules not FIPS 140-2 validated.',
        '3.13.13': 'Mobile code controls not deployed. No browser-level or network-level controls in place.',
        '3.13.14': 'VoIP not used in CUI environment. All voice communication via standard PSTN lines.',
        '3.13.15': 'TLS everywhere for web apps. Need session authentication for legacy protocols.',
        '3.13.16': 'CUI at rest protection planned. BitLocker on endpoints, TDE for databases scheduled Q2.',
        '3.14.4': 'AV signature updates automated on most systems. 15% of endpoints have stale definitions.',
        '3.14.5': 'Periodic scanning scheduled but not consistently executed. Real-time scanning for external files planned.',
        '3.14.6': 'No IDS/IPS deployed. Basic firewall logging only. Need comprehensive network monitoring solution.',
        '3.14.7': 'Unauthorized use detection not implemented. No baseline behavioral analysis in place.',
    }

    # Create all controls
    control_map = {}  # control_number -> control_id
    sort_counter = 0
    for family_code, ctrl_list in controls_data.items():
        fam_id = family_map[family_code]
        for number, title, req_text, plain, ctrl_type, weight in ctrl_list:
            sort_counter += 1
            ctrl_id = make_id(f'control-{number}')
            status = status_assignments.get(number, 'not_assessed')
            notes = impl_notes.get(number, '')
            assessed_date = '2026-01-15T10:00:00' if status != 'not_assessed' else None
            assessed_by = 'Security Analyst' if status != 'not_assessed' else None

            control = Control(
                id=ctrl_id,
                family_id=fam_id,
                control_number=number,
                title=title,
                requirement_text=req_text,
                plain_english=plain,
                guidance_text=f'For a small business, this means: {plain}',
                control_type=ctrl_type,
                implementation_status=status,
                weight=weight,
                sprs_points_if_not_met=-weight,
                implementation_notes=notes if notes else None,
                assessor_notes=None,
                last_assessed_date=assessed_date,
                assessed_by=assessed_by,
                sort_order=sort_counter,
                session_id='__default__',
            )
            db.session.add(control)
            control_map[number] = ctrl_id

    # =========================================================================
    # ASSESSMENT OBJECTIVES (~55 objectives across key controls)
    # =========================================================================
    objectives_data = [
        # AC family
        ('3.1.1[a]', '3.1.1', 'Determine if authorized users are identified.', 'satisfied'),
        ('3.1.1[b]', '3.1.1', 'Determine if processes acting on behalf of authorized users are identified.', 'satisfied'),
        ('3.1.1[c]', '3.1.1', 'Determine if devices (and other systems) authorized to connect are identified.', 'satisfied'),
        ('3.1.1[d]', '3.1.1', 'Determine if system access is limited to authorized users.', 'satisfied'),
        ('3.1.2[a]', '3.1.2', 'Determine if types of transactions and functions authorized users are permitted to execute are defined.', 'satisfied'),
        ('3.1.2[b]', '3.1.2', 'Determine if system access is limited to permitted types of transactions and functions.', 'satisfied'),
        ('3.1.5[a]', '3.1.5', 'Determine if privileged accounts are identified.', 'satisfied'),
        ('3.1.5[b]', '3.1.5', 'Determine if access to privileged accounts is authorized in accordance with least privilege.', 'satisfied'),
        ('3.1.5[c]', '3.1.5', 'Determine if access to security functions is authorized in accordance with least privilege.', 'satisfied'),
        ('3.1.12[a]', '3.1.12', 'Determine if remote access sessions are monitored.', 'satisfied'),
        ('3.1.12[b]', '3.1.12', 'Determine if remote access sessions are controlled.', 'other_than_satisfied'),
        ('3.1.13[a]', '3.1.13', 'Determine if cryptographic mechanisms are identified for remote access sessions.', 'satisfied'),
        ('3.1.13[b]', '3.1.13', 'Determine if cryptographic mechanisms protect confidentiality of remote access sessions.', 'satisfied'),
        # AT family
        ('3.2.1[a]', '3.2.1', 'Determine if managers are made aware of security risks.', 'satisfied'),
        ('3.2.1[b]', '3.2.1', 'Determine if users are made aware of applicable policies and procedures.', 'satisfied'),
        ('3.2.2[a]', '3.2.2', 'Determine if information security duties and responsibilities are assigned.', 'satisfied'),
        ('3.2.2[b]', '3.2.2', 'Determine if personnel are adequately trained for their roles.', 'satisfied'),
        # AU family
        ('3.3.1[a]', '3.3.1', 'Determine if audit logs are created.', 'satisfied'),
        ('3.3.1[b]', '3.3.1', 'Determine if audit logs are retained for the required period.', 'satisfied'),
        ('3.3.1[c]', '3.3.1', 'Determine if audit logs enable monitoring of unlawful activity.', 'satisfied'),
        ('3.3.2[a]', '3.3.2', 'Determine if system users can be uniquely identified.', 'satisfied'),
        ('3.3.2[b]', '3.3.2', 'Determine if actions can be traced to specific users.', 'satisfied'),
        # IA family
        ('3.5.1[a]', '3.5.1', 'Determine if system users are identified.', 'satisfied'),
        ('3.5.1[b]', '3.5.1', 'Determine if processes acting on behalf of users are identified.', 'satisfied'),
        ('3.5.1[c]', '3.5.1', 'Determine if devices are identified.', 'satisfied'),
        ('3.5.2[a]', '3.5.2', 'Determine if identities are authenticated for users.', 'satisfied'),
        ('3.5.2[b]', '3.5.2', 'Determine if identities are authenticated for processes.', 'satisfied'),
        ('3.5.2[c]', '3.5.2', 'Determine if identities are authenticated for devices.', 'satisfied'),
        ('3.5.3[a]', '3.5.3', 'Determine if MFA is used for local access to privileged accounts.', 'other_than_satisfied'),
        ('3.5.3[b]', '3.5.3', 'Determine if MFA is used for network access to privileged accounts.', 'satisfied'),
        ('3.5.3[c]', '3.5.3', 'Determine if MFA is used for network access to non-privileged accounts.', 'other_than_satisfied'),
        # IR family
        ('3.6.1[a]', '3.6.1', 'Determine if an incident-handling capability is established.', 'satisfied'),
        ('3.6.1[b]', '3.6.1', 'Determine if the capability includes preparation activities.', 'satisfied'),
        ('3.6.1[c]', '3.6.1', 'Determine if the capability includes detection and analysis.', 'satisfied'),
        ('3.6.1[d]', '3.6.1', 'Determine if the capability includes containment and recovery.', 'satisfied'),
        # CM family
        ('3.4.1[a]', '3.4.1', 'Determine if baseline configurations are established.', 'satisfied'),
        ('3.4.1[b]', '3.4.1', 'Determine if system inventories are maintained.', 'satisfied'),
        ('3.4.2[a]', '3.4.2', 'Determine if security configuration settings are established.', 'satisfied'),
        ('3.4.2[b]', '3.4.2', 'Determine if security configuration settings are enforced.', 'other_than_satisfied'),
        # SC family
        ('3.13.1[a]', '3.13.1', 'Determine if communications at external boundaries are monitored.', 'satisfied'),
        ('3.13.1[b]', '3.13.1', 'Determine if communications at external boundaries are controlled.', 'satisfied'),
        ('3.13.1[c]', '3.13.1', 'Determine if communications at key internal boundaries are monitored.', 'satisfied'),
        ('3.13.8[a]', '3.13.8', 'Determine if cryptographic mechanisms are identified for CUI transmission.', 'satisfied'),
        ('3.13.8[b]', '3.13.8', 'Determine if cryptographic mechanisms prevent unauthorized disclosure during transmission.', 'satisfied'),
        ('3.13.16[a]', '3.13.16', 'Determine if CUI at rest is identified.', 'satisfied'),
        ('3.13.16[b]', '3.13.16', 'Determine if confidentiality of CUI at rest is protected.', 'satisfied'),
        # SI family
        ('3.14.1[a]', '3.14.1', 'Determine if system flaws are identified.', 'satisfied'),
        ('3.14.1[b]', '3.14.1', 'Determine if system flaws are reported.', 'satisfied'),
        ('3.14.1[c]', '3.14.1', 'Determine if system flaws are corrected in a timely manner.', 'satisfied'),
        ('3.14.2[a]', '3.14.2', 'Determine if designated locations for malicious code protection are identified.', 'satisfied'),
        ('3.14.2[b]', '3.14.2', 'Determine if protection from malicious code is provided at designated locations.', 'satisfied'),
        ('3.14.6[a]', '3.14.6', 'Determine if organizational systems are monitored for attacks.', 'other_than_satisfied'),
        ('3.14.6[b]', '3.14.6', 'Determine if inbound and outbound traffic is monitored.', 'other_than_satisfied'),
        # RA family
        ('3.11.2[a]', '3.11.2', 'Determine if vulnerabilities are scanned periodically.', 'satisfied'),
        ('3.11.2[b]', '3.11.2', 'Determine if vulnerabilities are scanned when new vulnerabilities are identified.', 'other_than_satisfied'),
    ]

    for obj_num, ctrl_num, obj_text, status in objectives_data:
        obj_id = make_id(f'objective-{obj_num}')
        ctrl_id = control_map.get(ctrl_num)
        if ctrl_id:
            objective = AssessmentObjective(
                id=obj_id,
                control_id=ctrl_id,
                objective_number=obj_num,
                objective_text=obj_text,
                status=status,
                notes=None,
                session_id='__default__',
            )
            db.session.add(objective)

    # =========================================================================
    # EVIDENCE (18 items)
    # =========================================================================
    evidence_data = [
        ('Access Control Policy v2.1', '3.1.1', 'wiki_link',
         'Corporate access control policy covering user provisioning, role-based access, and deprovisioning procedures.',
         None, 'https://wiki.company.local/policies/access-control'),
        ('Active Directory Group Policy Export', '3.1.2', 'config',
         'GPO export showing role-based access controls and security group assignments.',
         '/evidence/ad-gpo-export-2026-01.xml', None),
        ('VPN Configuration Export', '3.1.13', 'config',
         'Palo Alto GlobalProtect VPN configuration showing AES-256 encryption and certificate authentication.',
         '/evidence/vpn-config-2026-01.json', None),
        ('Security Awareness Training Records Q4 2025', '3.2.1', 'document',
         'KnowBe4 training completion report showing 98% completion rate for annual security awareness training.',
         '/evidence/training-records-q4-2025.xlsx', None),
        ('Role-Based Security Training Matrix', '3.2.2', 'document',
         'Matrix mapping roles to required security training modules with completion tracking.',
         '/evidence/rbst-matrix-2026.xlsx', None),
        ('SIEM Audit Log Configuration', '3.3.1', 'screenshot',
         'Splunk configuration screenshots showing audit log collection from all CUI systems.',
         '/evidence/siem-audit-config.png', None),
        ('User Activity Logging Policy', '3.3.2', 'wiki_link',
         'Policy requiring unique user IDs and activity logging for all CUI system access.',
         None, 'https://wiki.company.local/policies/user-activity-logging'),
        ('System Inventory Spreadsheet', '3.4.1', 'document',
         'Complete hardware and software inventory for all systems in the CUI boundary.',
         '/evidence/system-inventory-2026-01.xlsx', None),
        ('CIS Benchmark Scan Results', '3.4.2', 'config',
         'CIS-CAT Pro scan results for Windows Server 2022 showing 87% compliance with Level 1 benchmark.',
         '/evidence/cis-scan-results-2026-01.html', None),
        ('MFA Configuration - Duo Security', '3.5.3', 'screenshot',
         'Duo Admin console showing MFA enforcement for all privileged accounts.',
         '/evidence/duo-mfa-config.png', None),
        ('Identity Provider Configuration', '3.5.2', 'config',
         'Azure AD configuration export showing authentication policies and conditional access rules.',
         '/evidence/azure-ad-config-2026-01.json', None),
        ('Incident Response Plan v3.0', '3.6.1', 'document',
         'Organizational incident response plan covering preparation, detection, containment, and recovery.',
         '/evidence/ir-plan-v3.pdf', None),
        ('Firewall Rule Export', '3.13.1', 'config',
         'Palo Alto firewall rule export showing boundary protection configuration and deny-by-default rules.',
         '/evidence/firewall-rules-2026-01.xml', None),
        ('TLS Certificate Inventory', '3.13.8', 'document',
         'Inventory of all TLS certificates used for encrypting CUI in transit.',
         '/evidence/tls-cert-inventory.xlsx', None),
        ('BitLocker Compliance Report', '3.13.16', 'screenshot',
         'Intune BitLocker compliance report showing encryption status of all managed endpoints.',
         '/evidence/bitlocker-compliance.png', None),
        ('CrowdStrike Dashboard Export', '3.14.2', 'screenshot',
         'CrowdStrike Falcon dashboard showing endpoint protection coverage and detection statistics.',
         '/evidence/crowdstrike-dashboard.png', None),
        ('Nessus Vulnerability Scan Report', '3.11.2', 'document',
         'Monthly Nessus vulnerability scan report for January 2026 showing 23 high, 45 medium findings.',
         '/evidence/nessus-scan-jan-2026.pdf', None),
        ('Background Check Process Document', '3.9.1', 'wiki_link',
         'HR process for conducting background checks prior to granting system access.',
         None, 'https://wiki.company.local/hr/background-checks'),
    ]

    for title, ctrl_num, etype, desc, fpath, url in evidence_data:
        ev_id = make_id(f'evidence-{title}')
        ctrl_id = control_map.get(ctrl_num)
        if ctrl_id:
            ev = Evidence(
                id=ev_id,
                control_id=ctrl_id,
                evidence_type=etype,
                title=title,
                description=desc,
                file_path=fpath,
                external_url=url,
                uploaded_at='2026-01-20T14:00:00',
                uploaded_by='admin',
                session_id='__default__',
            )
            db.session.add(ev)

    # =========================================================================
    # POA&M ITEMS (10 items)
    # =========================================================================
    poam_data = [
        ('3.5.3', 'Multifactor authentication not deployed for privileged or non-privileged accounts.',
         'Procure and deploy Duo MFA for all user accounts. Phase 1: Privileged accounts. Phase 2: VPN access. Phase 3: All network access.',
         'critical', 'John Smith', 'IT Security', '2026-01-15', '2026-05-15', None, 35000.0,
         'Duo licensing, integration labor, and user training', 'in_progress',
         '[{"description":"Duo license procurement","status":"completed"},{"description":"Phase 1 - Privileged accounts","status":"in_progress"},{"description":"Phase 2 - VPN access","status":"planned"},{"description":"Phase 3 - All network access","status":"planned"}]'),
        ('3.14.6', 'Insufficient network monitoring for attacks and indicators of compromise.',
         'Deploy comprehensive IDS/IPS solution with internal network visibility. Evaluate and deploy Suricata or commercial NIDS.',
         'high', 'Mike Johnson', 'IT Infrastructure', '2026-02-01', '2026-06-01', None, 45000.0,
         'Hardware sensors, software licenses, and implementation labor', 'open',
         '[{"description":"Solution evaluation","status":"in_progress"},{"description":"Hardware procurement","status":"planned"},{"description":"Deployment and tuning","status":"planned"}]'),
        ('3.8.3', 'No formal media sanitization procedures or equipment in place.',
         'Procure NIST 800-88 compliant degausser and media shredder. Document sanitization procedures and train staff.',
         'moderate', 'Sarah Williams', 'IT Operations', '2026-02-15', '2026-05-15', None, 8000.0,
         'Equipment purchase and procedure documentation', 'open',
         '[{"description":"Procedure documentation","status":"in_progress"},{"description":"Equipment procurement","status":"planned"},{"description":"Staff training","status":"planned"}]'),
        ('3.4.8', 'Application allowlisting not deployed on CUI systems.',
         'Evaluate and deploy application allowlisting solution (AppLocker or third-party). Start with servers, then extend to workstations.',
         'moderate', 'David Chen', 'IT Security', '2026-03-01', '2026-07-01', None, 15000.0,
         'Software licensing and deployment labor', 'open',
         '[{"description":"Solution evaluation","status":"planned"},{"description":"Server deployment","status":"planned"},{"description":"Workstation rollout","status":"planned"}]'),
        ('3.13.4', 'Shared system resources not fully controlled for information leakage.',
         'Implement shared resource controls on workstations. Review and configure temp file cleanup, clipboard policies, and print spooler security.',
         'moderate', 'Tom Wilson', 'IT Operations', '2026-03-15', '2026-06-15', None, 5000.0,
         'GPO configuration and testing labor', 'open',
         '[{"description":"Baseline assessment","status":"planned"},{"description":"GPO development","status":"planned"},{"description":"Testing and deployment","status":"planned"}]'),
        ('3.7.4', 'Maintenance media not scanned for malicious code before use.',
         'Establish procedure for scanning all maintenance media. Configure dedicated scanning workstation with updated AV.',
         'low', 'Sarah Williams', 'IT Operations', '2026-04-01', '2026-05-30', None, 2000.0,
         'Dedicated scanning workstation setup', 'open',
         '[{"description":"Procedure documentation","status":"planned"},{"description":"Scanning station setup","status":"planned"}]'),
        ('3.10.5', 'Physical access device inventory incomplete.',
         'Complete inventory of all keys, badges, and access cards. Implement check-in/check-out process and quarterly audits.',
         'low', 'Robert Brown', 'Facilities', '2026-02-01', '2026-04-30', None, 3000.0,
         'Badge system audit and process documentation', 'in_progress',
         '[{"description":"Badge inventory","status":"in_progress"},{"description":"Key inventory","status":"planned"},{"description":"Process documentation","status":"planned"}]'),
        ('3.13.13', 'Mobile code controls not comprehensively deployed.',
         'Develop mobile code policy and configure browser-level controls via GPO. Evaluate content filtering proxy for additional controls.',
         'low', 'David Chen', 'IT Security', '2026-04-01', '2026-06-30', None, 4000.0,
         'Policy development and GPO configuration', 'open',
         '[]'),
        ('3.3.9', 'Audit logging management not restricted to limited personnel.',
         'Implement RBAC for SIEM administration. Create separate admin roles for log management vs log viewing.',
         'moderate', 'Mike Johnson', 'IT Security', '2026-02-15', '2026-04-15', None, 3000.0,
         'SIEM RBAC configuration labor', 'open',
         '[{"description":"Role definition","status":"planned"},{"description":"RBAC implementation","status":"planned"},{"description":"Access review","status":"planned"}]'),
        ('3.13.11', 'FIPS-validated cryptography not employed for CUI protection.',
         'Identify all cryptographic modules in use. Replace non-FIPS modules with FIPS 140-2 validated alternatives. Update certificates and key stores.',
         'high', 'David Chen', 'IT Security', '2026-03-01', '2026-08-01', None, 30000.0,
         'FIPS module licensing, migration labor, and testing', 'open',
         '[{"description":"Cryptographic module inventory","status":"planned"},{"description":"FIPS module procurement","status":"planned"},{"description":"Migration and testing","status":"planned"}]'),
        ('3.12.4', 'System Security Plan not documented.',
         'Hire consultant or assign dedicated resource to develop comprehensive SSP covering all 110 controls, system boundary, data flows, and interconnections.',
         'high', 'Lisa Anderson', 'Compliance', '2025-12-01', '2026-04-01', None, 25000.0,
         'Consultant fees for SSP development', 'in_progress',
         '[{"description":"System boundary documentation","status":"completed"},{"description":"Control implementation descriptions","status":"in_progress"},{"description":"Data flow diagrams","status":"planned"},{"description":"Final review and approval","status":"planned"}]'),
    ]

    for ctrl_num, weakness, remediation, risk, person, team, start, end, actual, cost, cost_note, status, milestones in poam_data:
        poam_id = make_id(f'poam-{ctrl_num}-{weakness[:30]}')
        ctrl_id = control_map.get(ctrl_num)
        if ctrl_id:
            item = POAMItem(
                id=poam_id,
                control_id=ctrl_id,
                weakness_description=weakness,
                remediation_plan=remediation,
                risk_level=risk,
                responsible_person=person,
                responsible_team=team,
                planned_start_date=start,
                planned_completion_date=end,
                actual_completion_date=actual,
                estimated_cost=cost,
                cost_notes=cost_note,
                status=status,
                milestones=milestones,
                created_at='2026-01-15T10:00:00',
                updated_at='2026-02-01T10:00:00',
                session_id='__default__',
            )
            db.session.add(item)

    # =========================================================================
    # BOUNDARY ASSETS (10 items)
    # =========================================================================
    boundary_data = [
        ('CUI Enclave', 'SRV-001', 'CUI File Server', 'server', 'CUI', 1,
         'Windows Server 2022. Primary file server for CUI documents. BitLocker encrypted. Located in Server Room A.'),
        ('CUI Enclave', 'SRV-002', 'Exchange Server', 'server', 'CUI', 1,
         'Exchange Server 2019. Handles email containing CUI. TLS enforced for all connections.'),
        ('CUI Enclave', 'SRV-003', 'Domain Controller', 'server', 'CUI', 1,
         'Windows Server 2022 AD DS. Primary domain controller for the CUI enclave.'),
        ('CUI Enclave', 'SRV-004', 'Database Server', 'server', 'CUI', 1,
         'SQL Server 2022 on Windows Server 2022. Hosts applications that process CUI. TDE enabled.'),
        ('CUI Enclave', 'EP-GRP-001', 'Admin Laptops (8)', 'endpoint', 'CUI', 1,
         '8 Dell Latitude 5540 laptops. BitLocker encrypted. CrowdStrike Falcon agent. Assigned to IT and engineering staff.'),
        ('CUI Enclave', 'EP-GRP-002', 'Standard Workstations (25)', 'endpoint', 'CUI', 1,
         '25 Dell OptiPlex desktops. BitLocker encrypted. Used for general business operations with CUI access.'),
        ('CUI Enclave', 'NET-001', 'Palo Alto PA-850 Firewall', 'network', 'CUI', 1,
         'Primary perimeter firewall. Default-deny configuration. IDS/IPS enabled. Site-to-site VPN termination.'),
        ('Cloud Boundary', 'CLD-001', 'Microsoft 365 GCC', 'cloud', 'CUI', 1,
         'M365 GCC environment for email, SharePoint, and Teams. Configured for CUI handling per DFARS requirements.'),
        ('Cloud Boundary', 'CLD-002', 'AWS GovCloud', 'cloud', 'FCI', 1,
         'AWS GovCloud (US) for web application hosting. FedRAMP High authorized. Used for FCI processing.'),
        ('CUI Enclave', 'NET-002', 'Cisco Catalyst 9300 Switches (4)', 'network', 'CUI', 1,
         '4 Cisco Catalyst 9300 switches providing LAN connectivity. 802.1X NAC enabled. VLAN segmentation configured.'),
    ]

    for bname, tracker_id, aname, atype, classification, scope, notes in boundary_data:
        asset_id = make_id(f'boundary-{tracker_id}')
        asset = BoundaryAsset(
            id=asset_id,
            boundary_name=bname,
            asset_tracker_id=tracker_id,
            asset_name=aname,
            asset_type=atype,
            data_classification=classification,
            in_scope=scope,
            notes=notes,
            session_id='__default__',
        )
        db.session.add(asset)

    # =========================================================================
    # COMMIT
    # =========================================================================
    db.session.commit()
